NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Create.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;

namespace NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement
{
    public class CreateModel : PageModel
    {
        private readonly IAccountService _accountService;

        public CreateModel(IAccountService accountService)
        {
            _accountService = accountService;
        }

        [BindProperty]
        public SystemAccount Account { get; set; } = new();

        public IActionResult OnGet()
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "Admin")
            {
                return RedirectToPage("/Account/Login");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "Admin")
            {
                return RedirectToPage("/Account/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            _accountService.CreateAccount(Account);

            return RedirectToPage("./Index");
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Delete.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;

namespace NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement
{
    public class DeleteModel : PageModel
    {
        private readonly IAccountService _accountService;

        public DeleteModel(IAccountService accountService)
        {
            _accountService = accountService;
        }

        [BindProperty]
        public SystemAccount Account { get; set; } = default!;

        public IActionResult OnGet(short id)
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "Admin")
            {
                return RedirectToPage("/Account/Login");
            }

            var account = _accountService.GetAccountById(id);
            if (account == null)
            {
                return NotFound();
            }
            Account = account;
            return Page();
        }

        public IActionResult OnPost(short id)
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "Admin")
            {
                return RedirectToPage("/Account/Login");
            }

            var accountToDelete = _accountService.GetAccountById(id);
            if (accountToDelete == null)
            {
                return NotFound();
            }

            _accountService.DeleteAccount(accountToDelete);

            return RedirectToPage("./Index");
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Details.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;

namespace NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement
{
    public class DetailsModel : PageModel
    {
        private readonly IAccountService _accountService;

        public DetailsModel(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public SystemAccount Account { get; set; } = default!;

        public IActionResult OnGet(short id)
        {
            var account = _accountService.GetAccountById(id);
            if (account == null)
            {
                return NotFound();
            }
            Account = account;
            return Page();
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Edit.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;

namespace NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement
{
    public class EditModel : PageModel
    {
        private readonly IAccountService _accountService;

        public EditModel(IAccountService accountService)
        {
            _accountService = accountService;
        }

        [BindProperty]
        public SystemAccount Account { get; set; } = default!;

        public IActionResult OnGet(short id)
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "Admin")
            {
                return RedirectToPage("/Account/Login");
            }

            var account = _accountService.GetAccountById(id);
            if (account == null)
            {
                return NotFound();
            }
            Account = account;
            return Page();
        }

        public IActionResult OnPost()
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "Admin")
            {
                return RedirectToPage("/Account/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            _accountService.UpdateAccount(Account);

            return RedirectToPage("./Index");
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Index.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement
{
    public class IndexModel : PageModel
    {
        private readonly IAccountService _accountService;

        public IndexModel(IAccountService accountService)
        {
            _accountService = accountService;
        }

        public IList<SystemAccount> Accounts { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }

        [BindProperty]
        public SystemAccount Account { get; set; }

        private bool IsAdmin()
        {
            return HttpContext.Session.GetString("Role") == "Admin";
        }

        public IActionResult OnGet()
        {
            if (!IsAdmin()) return RedirectToPage("/Account/Login");

            Accounts = _accountService.GetAccounts(SearchTerm);
            return Page();
        }

        public IActionResult OnGetAccount(short id)
        {
            if (!IsAdmin()) return Unauthorized();

            var account = _accountService.GetAccountById(id);
            if (account == null)
            {
                return NotFound();
            }

            var result = new
            {
                accountId = account.AccountId,
                accountName = account.AccountName,
                accountEmail = account.AccountEmail,
                accountRole = account.AccountRole
            };

            return new JsonResult(result);
        }

        public IActionResult OnPostCreate()
        {
            if (!IsAdmin()) return RedirectToPage("/Account/Login");

            if (!ModelState.IsValid)
            {
                Accounts = _accountService.GetAccounts(SearchTerm);
                return Page();
            }

            _accountService.CreateAccount(Account);
            return RedirectToPage("./Index");
        }

        public IActionResult OnPostEdit()
        {
            if (!IsAdmin()) return RedirectToPage("/Account/Login");

            ModelState.Remove("Account.AccountPassword");

            if (!ModelState.IsValid)
            {
                Accounts = _accountService.GetAccounts(SearchTerm);
                return Page();
            }

            _accountService.UpdateAccount(Account);
            return RedirectToPage("./Index");
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Staff/CategoryManagement/Create.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;

namespace NguyenTrungThanhRazorPages.Pages.Staff.CategoryManagement
{
    public class CreateModel : PageModel
    {
        private readonly ICategoryService _categoryService;

        public CreateModel(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [BindProperty]
        public Category Category { get; set; } = new();

        public IActionResult OnGet()
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            _categoryService.SaveCategory(Category);
            return RedirectToPage("./Index");
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Staff/CategoryManagement/Delete.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;

namespace NguyenTrungThanhRazorPages.Pages.Staff.CategoryManagement
{
    public class DeleteModel : PageModel
    {
        private readonly ICategoryService _categoryService;

        public DeleteModel(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [BindProperty]
        public Category Category { get; set; } = default!;

        [TempData]
        public string ErrorMessage { get; set; }

        public IActionResult OnGet(short id)
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }

            var category = _categoryService.GetCategoryById(id);
            if (category == null)
            {
                return NotFound();
            }
            Category = category;
            return Page();
        }

        public IActionResult OnPost(short id)
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }

            if (_categoryService.IsCategoryInUse(id))
            {
                ErrorMessage = "Cannot delete this category because it is currently in use by one or more news articles.";
                return RedirectToPage("./Index");
            }

            var categoryToDelete = _categoryService.GetCategoryById(id);
            if (categoryToDelete != null)
            {
                _categoryService.DeleteCategory(categoryToDelete);
            }

            return RedirectToPage("./Index");
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Staff/CategoryManagement/Details.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;

namespace NguyenTrungThanhRazorPages.Pages.Staff.CategoryManagement
{
    public class DetailsModel : PageModel
    {
        private readonly ICategoryService _categoryService;

        public DetailsModel(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public Category Category { get; set; } = default!;

        public IActionResult OnGet(short id)
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }

            var category = _categoryService.GetCategoryById(id);
            if (category == null)
            {
                return NotFound();
            }
            Category = category;
            return Page();
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Staff/CategoryManagement/Edit.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Interfaces;

namespace NguyenTrungThanhRazorPages.Pages.Staff.CategoryManagement
{
    public class EditModel : PageModel
    {
        private readonly ICategoryService _categoryService;

        public EditModel(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [BindProperty]
        public Category Category { get; set; } = default!;

        public IActionResult OnGet(short id)
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }

            var category = _categoryService.GetCategoryById(id);
            if (category == null)
            {
                return NotFound();
            }
            Category = category;
            return Page();
        }

        public IActionResult OnPost()
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            _categoryService.UpdateCategory(Category);
            return RedirectToPage("./Index");
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Staff/NewsManagement/Create.cshtml.cs
using BusinessObjects;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Interfaces;
using System;
using System.Linq;
using Microsoft.AspNetCore.SignalR;
using NguyenTrungThanhRazorPages.Hubs;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace NguyenTrungThanhRazorPages.Pages.Staff.NewsManagement
{
    public class CreateModel : PageModel
    {
        private readonly INewsArticleService _newsArticleService;
        private readonly ICategoryService _categoryService;
        private readonly ITagService _tagService; 
        private readonly IHubContext<NewsHub> _hubContext;

        public CreateModel(INewsArticleService newsArticleService, ICategoryService categoryService, ITagService tagService, IHubContext<NewsHub> hubContext)
        {
            _newsArticleService = newsArticleService;
            _categoryService = categoryService;
            _tagService = tagService; 
            _hubContext = hubContext;
        }

        [BindProperty]
        public NewsArticle NewsArticle { get; set; } = new();

        [BindProperty]
        public string TagsString { get; set; }

        public SelectList CategoryList { get; set; }

        public IActionResult OnGet()
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }

            CategoryList = new SelectList(_categoryService.GetCategories(), "CategoryId", "CategoryName");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var userRole = HttpContext.Session.GetString("Role");
            if (userRole != "1")
            {
                return RedirectToPage("/Account/Login");
            }

            if (!ModelState.IsValid)
            {
                CategoryList = new SelectList(_categoryService.GetCategories(), "CategoryId", "CategoryName");
                return Page();
            }

            var accountId = HttpContext.Session.GetInt32("AccountId");
            if (accountId == null)
            {
                return RedirectToPage("/Account/Login");
            }

            NewsArticle.NewsArticleId = Guid.NewGuid().ToString();
            NewsArticle.CreatedById = (short)accountId;
            NewsArticle.CreatedDate = DateTime.Now;
            NewsArticle.NewsStatus = true;

            var tagNames = TagsString?.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) ?? Array.Empty<string>();
            var newTagsList = new List<NewsTag>();
            foreach (var tagName in tagNames)
            {
                var tag = _tagService.GetOrCreateTagByName(tagName);
                newTagsList.Add(new NewsTag { NewsArticleId = NewsArticle.NewsArticleId, TagId = tag.TagId });
            }
            NewsArticle.NewsTags = newTagsList;

            _newsArticleService.SaveNewsArticle(NewsArticle);
            await _hubContext.Clients.All.SendAsync("LoadNews");
            return RedirectToPage("./Index");
        }
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Create.cshtml
@page
@model NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement.CreateModel
@{
    ViewData["Title"] = "Create Account";
}

<h1>Create New Account</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group mb-3">
                <label asp-for="Account.AccountName" class="control-label"></label>
                <input asp-for="Account.AccountName" class="form-control" />
                <span asp-validation-for="Account.AccountName" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Account.AccountEmail" class="control-label"></label>
                <input asp-for="Account.AccountEmail" class="form-control" />
                <span asp-validation-for="Account.AccountEmail" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Account.AccountPassword" class="control-label"></label>
                <input asp-for="Account.AccountPassword" type="password" class="form-control" />
                <span asp-validation-for="Account.AccountPassword" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label asp-for="Account.AccountRole" class="control-label"></label>
                <input asp-for="Account.AccountRole" class="form-control" />
                <span asp-validation-for="Account.AccountRole" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-page="./Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Delete.cshtml
@page "{id:int}"
@model NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement.DeleteModel
@{
    ViewData["Title"] = "Delete Account";
}

<h1>Delete Account</h1>
<h3>Are you sure you want to delete this?</h3>
<hr />

<div>
    <h4>Account Details</h4>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.AccountName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.AccountName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.AccountEmail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.AccountEmail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Account.AccountRole)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Account.AccountRole)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Account.AccountId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Details.cshtml
@page "{id:int}"
@model NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement.DetailsModel
@{
    ViewData["Title"] = "Account Details";
}

<h1>Account Details</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">ID</dt>
        <dd class="col-sm-10">@Model.Account.AccountId</dd>

        <dt class="col-sm-2">Name</dt>
        <dd class="col-sm-10">@Model.Account.AccountName</dd>

        <dt class="col-sm-2">Email</dt>
        <dd class="col-sm-10">@Model.Account.AccountEmail</dd>

        <dt class="col-sm-2">Role</dt>
        <dd class="col-sm-10">@Model.Account.AccountRole</dd>
    </dl>
</div>
<div class="mt-3">
    <a asp-page="./Edit" asp-route-id="@Model.Account.AccountId" class="btn btn-primary">Edit</a>
    <a asp-page="./Index" class="btn btn-secondary">Back to List</a>
</div>

NguyenTrungThanh_SE18C.NET_A02/NguyenTrungThanhRazorPages/Pages/Admin/AccountManagement/Index.cshtml
@page
@model NguyenTrungThanhRazorPages.Pages.Admin.AccountManagement.IndexModel
@{
    ViewData["Title"] = "Account Management";
}

<div class="content-card">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="page-title mb-0">@ViewData["Title"]</h1>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createAccountModal">
            <i class="fa-solid fa-plus me-2"></i>Create New Account
        </button>
    </div>

    <div class="mb-4">
        <form method="get" class="d-flex">
            <input type="text" asp-for="SearchTerm" class="form-control me-2" placeholder="Enter name or email to search..." />
            <button type="submit" class="btn btn-info text-nowrap"><i class="fa-solid fa-search me-2"></i>Search</button>
        </form>
    </div>

    <table class="table table-custom">
        <thead>
            <tr>
                <th>ID</th>
                <th>Account Name</th>
                <th>Email</th>
                <th class="text-center">Role</th>
                <th class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Accounts)
            {
                <tr>
                    <td>@item.AccountId</td>
                    <td>@item.AccountName</td>
                    <td>@item.AccountEmail</td>
                    <td class="text-center">
                        @if (item.AccountRole == 1)
                        {
                            <span class="badge-role badge-role-staff">Staff</span>
                        }
                        else if (item.AccountRole == 2)
                        {
                            <span class="badge-role badge-role-lecturer">Lecturer</span>
                        }
                        else
                        {
                            @item.AccountRole
                        }
                    </td>
                    <td class="text-center action-buttons">
                        <button type="button" class="btn btn-action-edit edit-button" data-id="@item.AccountId" title="Edit">
                            <i class="fa-solid fa-pencil"></i>
                        </button>
                        <a asp-page="./Details" asp-route-id="@item.AccountId" class="btn btn-action-details" title="Details">
                            <i class="fa-solid fa-eye"></i>
                        </a>
                        <a asp-page="./Delete" asp-route-id="@item.AccountId" class="btn btn-action-delete" title="Delete" onclick="return confirm('Are you sure you want to delete this account?');">
                            <i class="fa-solid fa-trash-can"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="createAccountModal" tabindex="-1" aria-labelledby="createAccountModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" asp-page-handler="Create">
                <div class="modal-header">
                    <h5 class="modal-title" id="createAccountModalLabel">Create New Account</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                    <div class="form-group mb-3">
                        <label asp-for="Account.AccountName" class="form-label"></label>
                        <input asp-for="Account.AccountName" class="form-control" />
                        <span asp-validation-for="Account.AccountName" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Account.AccountEmail" class="form-label"></label>
                        <input asp-for="Account.AccountEmail" class="form-control" />
                        <span asp-validation-for="Account.AccountEmail" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Account.AccountPassword" class="form-label"></label>
                        <input asp-for="Account.AccountPassword" type="password" class="form-control" />
                        <span asp-validation-for="Account.AccountPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Account.AccountRole" class="form-label"></label>
                        <input asp-for="Account.AccountRole" class="form-control" placeholder="1 for Staff, 2 for Lecturer" />
                        <span asp-validation-for="Account.AccountRole" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="editAccountModal" tabindex="-1" aria-labelledby="editAccountModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" asp-page-handler="Edit">
                <div class="modal-header">
                    <h5 class="modal-title" id="editAccountModalLabel">Edit Account</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" asp-for="Account.AccountId" id="edit-account-id" />
                    <div class="form-group mb-3">
                        <label asp-for="Account.AccountName" class="form-label"></label>
                        <input asp-for="Account.AccountName" class="form-control" id="edit-account-name" />
                        <span asp-validation-for="Account.AccountName" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Account.AccountEmail" class="form-label"></label>
                        <input asp-for="Account.AccountEmail" class="form-control" id="edit-account-email" />
                        <span asp-validation-for="Account.AccountEmail" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Account.AccountPassword" class="form-label"></label>
                        <input asp-for="Account.AccountPassword" type="password" class="form-control" placeholder="Leave blank to keep current password" />
                        <span asp-validation-for="Account.AccountPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-3">
                        <label asp-for="Account.AccountRole" class="form-label"></label>
                        <input asp-for="Account.AccountRole" class="form-control" id="edit-account-role" />
                        <span asp-validation-for="Account.AccountRole" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $('.edit-button').on('click', function () {
                var accountId = $(this).data('id');
                $.ajax({
                    url: `/Admin/AccountManagement?handler=Account&id=${accountId}`,
                    type: 'GET',
                    success: function (response) {
                        $('#edit-account-id').val(response.accountId);
                        $('#edit-account-name').val(response.accountName);
                        $('#edit-account-email').val(response.accountEmail);
                        $('#edit-account-role').val(String(response.accountRole));

                        var editModal = new bootstrap.Modal(document.getElementById('editAccountModal'));
                        editModal.show();
                    },
                    error: function () {
                        alert('Could not retrieve account details.');
                    }
                });
            });

            $('#createAccountModal').on('hidden.bs.modal', function () {
                $(this).find('form')[0].reset();
                $(this).find('.text-danger').text('');
            });
        });
    </script>
}